# Generated by Django 5.0.6 on 2024-08-18 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="channel_id",
            field=models.CharField(
                help_text="Distinct identifier for each conversation.",
                max_length=255,
                verbose_name="Channel ID",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time marking the start of the conversation.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                help_text="The actual text of the message.", verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                help_text="The chat channel this message belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chatapp.conversation",
                verbose_name="Conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                help_text="The user responsible for this message.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time marking when the message was dispatched.",
                verbose_name="Timestamp",
            ),
        ),
    ]
