# Generated by Django 5.0.6 on 2024-08-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="account",
            name="username",
        ),
        migrations.AddField(
            model_name="account",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Check this if you wish to enable two-factor authentication.",
                verbose_name="Is 2FA Enabled",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_2fa_setup_in_progress",
            field=models.BooleanField(
                default=False,
                help_text="Tracks whether the 2FA setup process is ongoing",
                verbose_name="Is 2FA Setup in Progress",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="tfa_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Secret key for two-factor authentication. Leave blank if unsure.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                help_text="Enter your email address. Used for login.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(
                help_text="Enter your first name.",
                max_length=26,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(
                help_text="Enter your last name.",
                max_length=26,
                verbose_name="Last Name",
            ),
        ),
    ]
