# Generated by Django 5.0.6 on 2024-08-15 19:06

import django.db.models.deletion
import server.utils.image_path
import server.validators.image_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_category_icon_alter_server_banner_img_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the category.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                default=server.utils.image_path.default_category_icon,
                help_text="An optional icon for the category.",
                null=True,
                upload_to=server.utils.image_path.category_icon_upload_path,
                validators=[
                    server.validators.image_validators.validate_icon_image_size,
                    server.validators.image_validators.validate_image_file_extension,
                ],
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="The name of the category.",
                max_length=50,
                verbose_name="Category Name",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(
                help_text="The name of the channel, which users will see and use to identify the chat room.",
                max_length=50,
                verbose_name="Channel Name",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who owns the channel.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Channel Owner",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="server",
            field=models.ForeignKey(
                help_text="The server to which this channel belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_server",
                to="server.server",
                verbose_name="Server",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="topic",
            field=models.CharField(
                help_text="A short description or topic of the channel.",
                max_length=100,
                verbose_name="Channel Topic",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="banner_img",
            field=models.ImageField(
                blank=True,
                default=server.utils.image_path.default_server_banner_img_path,
                help_text="An optional banner image for the server.",
                null=True,
                upload_to=server.utils.image_path.server_banner_img_upload_path,
                validators=[
                    server.validators.image_validators.validate_image_file_extension
                ],
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="category",
            field=models.ForeignKey(
                help_text="The category to which this server belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_category",
                to="server.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="A brief description of the server.",
                max_length=250,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="An optional icon for the server.",
                null=True,
                upload_to=server.utils.image_path.server_icon_upload_path,
                validators=[
                    server.validators.image_validators.validate_image_file_extension
                ],
                verbose_name="Icon",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="members",
            field=models.ManyToManyField(
                help_text="The users who are members of this server.",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Members",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(
                help_text="The name of the server.",
                max_length=50,
                verbose_name="Server Name",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who owns the server.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Server Owner",
            ),
        ),
    ]
